
language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules

script:
  - npm run pages
jobs:
  include:
    - stage: ghpages
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: assets
        on:
          branch: master
    - stage: deploy
      script: npm run build
      deploy:
        provider: npm
        email: supermanchc@gmail.com
        api_key: $NPM_KEY
        skip-cleanup: true
        on:
          tags: true

# You can specify the order for stages
stages:
  - name: ghpages
  - name: deploy
    if: tag IS present # conditional build, only deploy when tag is present